# Generated by Django 3.2.15 on 2022-09-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_pofilefeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PofileFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
